# This is an example configuration file
# To learn more, see the full config.yaml reference: https://docs.continue.dev/reference

name: DeepSeek-V3-0324 Config
version: 1.0.0
schema: v1

# Define which models can be used
# https://docs.continue.dev/customization/models
models:
  - name: "DeepSeek V3 0324"
    provider: openai
    model: deepseek-ai/DeepSeek-V3-0324
    apiKey: cpk_cd74b607fa944db3b94789603df42786.632683f5d41b5693a46ac03437d6cb1a.xalcrsPc4RVy2KhB4Q80VPB7YCyHR12w
    apiBase: https://api.lorebary.com/chutes/v1

# MCP Servers that Continue can access
# https://docs.continue.dev/customization/mcp-tools
mcpServers:
  - uses: anthropic/memory-mcp

